### ISSUE TITLE
Still get image of storyboard

### ISSUE THREAD

**Issue by davidlondono** [instilio/INSImageView#7]
when i set an image on it, the image setted on the storyboard still appear on background behind the new image

**Comment by ptrkstr** [comment]
Hi @davidlondono, is this what is happening?
- Dragging a UIImageView onto storyboard and settings its class to INSImageView
- Setting an image in Attributes Panel
- Seeing two images during app running

If this is correct, I'll look into it as soon as I get the chance.

**Comment by davidlondono** [comment]
after setting the image on the attribute Panel, on code I may change the image some times, so the image that i selected on the storyboard appear behind the new one

I made a pull request some time ago, when i was setting the super.image to nil, You said it wasn't necessary, I think that now it is :D

**Comment by ptrkstr** [comment]
This project is now deprecated and instead development will continue here https://github.com/patrickbdev/PBImageView
I've included instructions on how to use it in a storyboard.
