### ISSUE TITLE
Support for Swift 3.0

### ISSUE THREAD

**Issue by gchristov** [instilio/INSImageView#8]
Any plans for adding support for Swift 3.0?

**Comment by ptrkstr** [comment]
Hi @8masterofpuppets8, I should get time to do it within the next two weeks.

**Comment by Finb** [comment]
Xcode 8 can automatically convert this project to swift 3 syntax

**Comment by ptrkstr** [comment]
I'm closing the github instilio organisation and so this pod will be deprecated.
Development will continue here https://github.com/patrickbdev/PBImageView
INSImageView will now be PBImageView.
PBImageView begins from Swift 3.0 and is ready to be used immediately 😃

**Comment by gchristov** [comment]
Thanks! You will keep the previous version around for a while, right?

**Comment by ptrkstr** [comment]
Yep will keep it around, will just be marked deprecated in the podspec.
